<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Data guru dengan alamat di Lampung
        $teachers = [
            // ==================== WALI KELAS (18 guru) ====================
            // Kelas 1
            [
                'user_id' => null,
                'nip' => '197805152000121001',
                'nama_lengkap' => 'Dr. Ahmad Hidayat, M.Pd.',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Bandar Lampung',
                'tanggal_lahir' => '1978-05-15',
                'agama' => 'Islam',
                'nik' => '1871051505780001',
                'nomor_telepon' => '081234567890',
                'email' => 'ahmad.hidayat@sekolah.sch.id',
                'alamat' => 'Jl. Wolter Monginsidi No. 12',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Kota Bandar Lampung',
                'kecamatan' => 'Tanjungkarang Timur',
                'kelurahan' => 'Sukarame',
                'dusun' => 'Sukarame I',
                'kode_pos' => '35121',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2015-08-01',
            ],
            [
                'user_id' => null,
                'nip' => '198206202006042002',
                'nama_lengkap' => 'Siti Nurhaliza, S.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Metro',
                'tanggal_lahir' => '1982-06-20',
                'agama' => 'Islam',
                'nik' => '1872062006820002',
                'nomor_telepon' => '081298765432',
                'email' => 'siti.nurhaliza@sekolah.sch.id',
                'alamat' => 'Jl. Jenderal Sudirman No. 8',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Kota Metro',
                'kecamatan' => 'Metro Timur',
                'kelurahan' => 'Iringmulyo',
                'dusun' => 'Iringmulyo Timur',
                'kode_pos' => '34111',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2010-07-15',
            ],
            [
                'user_id' => null,
                'nip' => '199012102015032003',
                'nama_lengkap' => 'Budi Santoso, S.Pd.',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lampung Selatan',
                'tanggal_lahir' => '1990-12-10',
                'agama' => 'Kristen',
                'nik' => '1873121012900003',
                'nomor_telepon' => '082112345678',
                'email' => 'budi.santoso@sekolah.sch.id',
                'alamat' => 'Jl. Lintas Barat No. 45',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Lampung Selatan',
                'kecamatan' => 'Kalianda',
                'kelurahan' => 'Kalianda',
                'dusun' => 'Kalianda Utara',
                'kode_pos' => '35551',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2018-01-10',
            ],

            // Kelas 2
            [
                'user_id' => null,
                'nip' => '198508032010042004',
                'nama_lengkap' => 'Maria Ulfah, M.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Lampung Tengah',
                'tanggal_lahir' => '1985-08-03',
                'agama' => 'Katolik',
                'nik' => '1874080308850004',
                'nomor_telepon' => '081345678901',
                'email' => 'maria.ulfah@sekolah.sch.id',
                'alamat' => 'Jl. Protokol No. 23',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Lampung Tengah',
                'kecamatan' => 'Gunung Sugih',
                'kelurahan' => 'Gunung Sugih',
                'dusun' => 'Gunung Sugih Raya',
                'kode_pos' => '34161',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2012-03-15',
            ],
            [
                'user_id' => null,
                'nip' => '199105102018032101',
                'nama_lengkap' => 'Rina Wulandari, S.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Bandar Lampung',
                'tanggal_lahir' => '1991-05-10',
                'agama' => 'Islam',
                'nik' => '1871051005910001',
                'nomor_telepon' => '081212345678',
                'email' => 'rina.wulandari@sekolah.sch.id',
                'alamat' => 'Jl. Kartini No. 15',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Kota Bandar Lampung',
                'kecamatan' => 'Telukbetung Barat',
                'kelurahan' => 'Telukbetung',
                'dusun' => 'Telukbetung Selatan',
                'kode_pos' => '35211',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2019-01-15',
            ],
            [
                'user_id' => null,
                'nip' => '198911152014032102',
                'nama_lengkap' => 'Joko Susilo, S.Pd.',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lampung Timur',
                'tanggal_lahir' => '1989-11-15',
                'agama' => 'Islam',
                'nik' => '1874111508890002',
                'nomor_telepon' => '082212345678',
                'email' => 'joko.susilo@sekolah.sch.id',
                'alamat' => 'Jl. Raya Labuhan Ratu No. 20',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Lampung Timur',
                'kecamatan' => 'Labuhan Ratu',
                'kelurahan' => 'Labuhan Ratu',
                'dusun' => 'Labuhan Ratu Timur',
                'kode_pos' => '34396',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2016-07-20',
            ],

            // Kelas 3
            [
                'user_id' => null,
                'nip' => '199308252020032103',
                'nama_lengkap' => 'Diana Sari, S.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Pringsewu',
                'tanggal_lahir' => '1993-08-25',
                'agama' => 'Islam',
                'nik' => '1878082508930003',
                'nomor_telepon' => '081312345678',
                'email' => 'diana.sari@sekolah.sch.id',
                'alamat' => 'Jl. Raya Pringsewu No. 18',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Pringsewu',
                'kecamatan' => 'Pringsewu Selatan',
                'kelurahan' => 'Pringsewu Utara',
                'dusun' => 'Pringsewu Barat',
                'kode_pos' => '35373',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2021-02-10',
            ],
            [
                'user_id' => null,
                'nip' => '198704152009032104',
                'nama_lengkap' => 'Hendra Gunawan, M.Pd.',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Tanggamus',
                'tanggal_lahir' => '1987-04-15',
                'agama' => 'Islam',
                'nik' => '1874041504870004',
                'nomor_telepon' => '082312345678',
                'email' => 'hendra.gunawan@sekolah.sch.id',
                'alamat' => 'Jl. Raya Kota Agung No. 12',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Tanggamus',
                'kecamatan' => 'Kota Agung Timur',
                'kelurahan' => 'Kota Agung',
                'dusun' => 'Kota Agung Pusat',
                'kode_pos' => '35384',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2011-06-15',
            ],
            [
                'user_id' => null,
                'nip' => '199210102019032105',
                'nama_lengkap' => 'Fitriani Dewi, S.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Lampung Barat',
                'tanggal_lahir' => '1992-10-10',
                'agama' => 'Islam',
                'nik' => '1876101010920005',
                'nomor_telepon' => '081412345678',
                'email' => 'fitriani.dewi@sekolah.sch.id',
                'alamat' => 'Jl. Lintas Liwa No. 8',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Lampung Barat',
                'kecamatan' => 'Balik Bukit',
                'kelurahan' => 'Way Mengaku',
                'dusun' => 'Way Mengaku Barat',
                'kode_pos' => '34815',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2020-03-01',
            ],

            // Kelas 4
            [
                'user_id' => null,
                'nip' => '198012102002032106',
                'nama_lengkap' => 'Surya Adi, M.Pd.',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Way Kanan',
                'tanggal_lahir' => '1980-12-10',
                'agama' => 'Islam',
                'nik' => '1879121012800006',
                'nomor_telepon' => '081512345678',
                'email' => 'surya.adi@sekolah.sch.id',
                'alamat' => 'Jl. Raya Blambangan Umpu No. 25',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Way Kanan',
                'kecamatan' => 'Blambangan Umpu',
                'kelurahan' => 'Blambangan Umpu',
                'dusun' => 'Blambangan Umpu Timur',
                'kode_pos' => '34764',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2004-07-01',
            ],
            [
                'user_id' => null,
                'nip' => '199404202022032107',
                'nama_lengkap' => 'Rizka Amelia, S.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Bandar Lampung',
                'tanggal_lahir' => '1994-04-20',
                'agama' => 'Islam',
                'nik' => '1871042004940007',
                'nomor_telepon' => '081612345678',
                'email' => 'rizka.amelia@sekolah.sch.id',
                'alamat' => 'Jl. Pramuka No. 45',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Kota Bandar Lampung',
                'kecamatan' => 'Kedaton',
                'kelurahan' => 'Kedaton',
                'dusun' => 'Kedaton Timur',
                'kode_pos' => '35141',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2023-01-15',
            ],
            [
                'user_id' => null,
                'nip' => '198709052012032108',
                'nama_lengkap' => 'Agus Setiawan, S.Pd.',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lampung Tengah',
                'tanggal_lahir' => '1987-09-05',
                'agama' => 'Islam',
                'nik' => '1874090509870008',
                'nomor_telepon' => '082412345678',
                'email' => 'agus.setiawan@sekolah.sch.id',
                'alamat' => 'Jl. Raya Terbanggi Besar No. 30',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Lampung Tengah',
                'kecamatan' => 'Terbanggi Besar',
                'kelurahan' => 'Terbanggi Besar',
                'dusun' => 'Terbanggi Besar Selatan',
                'kode_pos' => '34163',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2014-08-20',
            ],

            // Kelas 5
            [
                'user_id' => null,
                'nip' => '199112152018032109',
                'nama_lengkap' => 'Maya Indah, S.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Metro',
                'tanggal_lahir' => '1991-12-15',
                'agama' => 'Islam',
                'nik' => '1872121512910009',
                'nomor_telepon' => '081712345678',
                'email' => 'maya.indah@sekolah.sch.id',
                'alamat' => 'Jl. Basuki Rahmat No. 22',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Kota Metro',
                'kecamatan' => 'Metro Pusat',
                'kelurahan' => 'Yosodadi',
                'dusun' => 'Yosodadi Timur',
                'kode_pos' => '34113',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2019-06-10',
            ],
            [
                'user_id' => null,
                'nip' => '198305202007032110',
                'nama_lengkap' => 'Rudi Hartono, M.Pd.',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lampung Selatan',
                'tanggal_lahir' => '1983-05-20',
                'agama' => 'Islam',
                'nik' => '1873052005830010',
                'nomor_telepon' => '082512345678',
                'email' => 'rudi.hartono@sekolah.sch.id',
                'alamat' => 'Jl. Lintas Barat No. 88',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Lampung Selatan',
                'kecamatan' => 'Kalianda',
                'kelurahan' => 'Merak Belatung',
                'dusun' => 'Merak Belatung Barat',
                'kode_pos' => '35551',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2009-01-15',
            ],
            [
                'user_id' => null,
                'nip' => '199511052021032111',
                'nama_lengkap' => 'Nur Aisyah, S.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Pesisir Barat',
                'tanggal_lahir' => '1995-11-05',
                'agama' => 'Islam',
                'nik' => '1872110511950011',
                'nomor_telepon' => '081812345678',
                'email' => 'nur.aisyah@sekolah.sch.id',
                'alamat' => 'Jl. Raya Krui No. 15',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Pesisir Barat',
                'kecamatan' => 'Krui',
                'kelurahan' => 'Krui',
                'dusun' => 'Krui Utara',
                'kode_pos' => '34874',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2022-02-20',
            ],

            // Kelas 6
            [
                'user_id' => null,
                'nip' => '198806152011032112',
                'nama_lengkap' => 'Fajar Nugroho, M.Pd.',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lampung Timur',
                'tanggal_lahir' => '1988-06-15',
                'agama' => 'Islam',
                'nik' => '1874061506880012',
                'nomor_telepon' => '082612345678',
                'email' => 'fajar.nugroho@sekolah.sch.id',
                'alamat' => 'Jl. Raya Sukadana No. 40',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Lampung Timur',
                'kecamatan' => 'Sukadana',
                'kelurahan' => 'Sukadana',
                'dusun' => 'Sukadana Barat',
                'kode_pos' => '34194',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2013-03-15',
            ],
            [
                'user_id' => null,
                'nip' => '199303102020032113',
                'nama_lengkap' => 'Lina Marlina, S.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Lampung Utara',
                'tanggal_lahir' => '1993-03-10',
                'agama' => 'Islam',
                'nik' => '1880031003930013',
                'nomor_telepon' => '081912345678',
                'email' => 'lina.marlina@sekolah.sch.id',
                'alamat' => 'Jl. Raya Kotabumi No. 33',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Lampung Utara',
                'kecamatan' => 'Kotabumi',
                'kelurahan' => 'Kotabumi',
                'dusun' => 'Kotabumi Pusat',
                'kode_pos' => '34511',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2021-07-01',
            ],
            [
                'user_id' => null,
                'nip' => '197912102000032114',
                'nama_lengkap' => 'Prof. Dr. Sri Mulyani, M.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Way Kanan',
                'tanggal_lahir' => '1979-12-10',
                'agama' => 'Islam',
                'nik' => '1879121012790014',
                'nomor_telepon' => '081890123456',
                'email' => 'sri.mulyani@sekolah.sch.id',
                'alamat' => 'Jl. Raya Blambangan Umpu No. 30',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Way Kanan',
                'kecamatan' => 'Blambangan Umpu',
                'kelurahan' => 'Blambangan Umpu',
                'dusun' => 'Blambangan Umpu Kota',
                'kode_pos' => '34764',
                'jabatan' => 'Wali Kelas',
                'status' => 'Aktif',
                'tanggal_masuk' => '2002-06-01',
            ],

            // ==================== GURU OLAHRAGA (6 guru) ====================
            // Guru Olahraga Kelas 1
            [
                'user_id' => null,
                'nip' => '198904152012051005',
                'nama_lengkap' => 'Rizki Pratama, S.Pd.',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Bandar Lampung',
                'tanggal_lahir' => '1989-04-15',
                'agama' => 'Islam',
                'nik' => '1871051504890005',
                'nomor_telepon' => '081512345678',
                'email' => 'rizki.pratama@sekolah.sch.id',
                'alamat' => 'Jl. Teuku Umar No. 7',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Kota Bandar Lampung',
                'kecamatan' => 'Tanjungkarang Pusat',
                'kelurahan' => 'Palapa',
                'dusun' => 'Palapa Raya',
                'kode_pos' => '35112',
                'jabatan' => 'Guru Olahraga',
                'status' => 'Aktif',
                'tanggal_masuk' => '2014-06-01',
            ],

            // Guru Olahraga Kelas 2
            [
                'user_id' => null,
                'nip' => '199203202018032006',
                'nama_lengkap' => 'Dewi Fitriani, S.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Lampung Timur',
                'tanggal_lahir' => '1992-03-20',
                'agama' => 'Islam',
                'nik' => '1875032003920006',
                'nomor_telepon' => '082345678901',
                'email' => 'dewi.fitriani@sekolah.sch.id',
                'alamat' => 'Jl. Raya Sukadana No. 15',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Lampung Timur',
                'kecamatan' => 'Sukadana',
                'kelurahan' => 'Sukadana',
                'dusun' => 'Sukadana Ilir',
                'kode_pos' => '34194',
                'jabatan' => 'Guru Olahraga',
                'status' => 'Aktif',
                'tanggal_masuk' => '2019-07-20',
            ],

            // Guru Olahraga Kelas 3
            [
                'user_id' => null,
                'nip' => '199008152017032201',
                'nama_lengkap' => 'Ahmad Yani, S.Pd.',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lampung Tengah',
                'tanggal_lahir' => '1990-08-15',
                'agama' => 'Islam',
                'nik' => '1874081508900001',
                'nomor_telepon' => '082112345678',
                'email' => 'ahmad.yani@sekolah.sch.id',
                'alamat' => 'Jl. Raya Gunung Sugih No. 25',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Lampung Tengah',
                'kecamatan' => 'Gunung Sugih',
                'kelurahan' => 'Gunung Sugih Barat',
                'dusun' => 'Gunung Sugih Raya',
                'kode_pos' => '34161',
                'jabatan' => 'Guru Olahraga',
                'status' => 'Aktif',
                'tanggal_masuk' => '2018-03-10',
            ],

            // Guru Olahraga Kelas 4
            [
                'user_id' => null,
                'nip' => '198511102010032202',
                'nama_lengkap' => 'Sari Wulandari, S.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Tanggamus',
                'tanggal_lahir' => '1985-11-10',
                'agama' => 'Islam',
                'nik' => '1877111011850002',
                'nomor_telepon' => '081234567890',
                'email' => 'sari.wulandari@sekolah.sch.id',
                'alamat' => 'Jl. Raya Kota Agung No. 8',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Tanggamus',
                'kecamatan' => 'Kota Agung',
                'kelurahan' => 'Kota Agung Barat',
                'dusun' => 'Kota Agung Pusat',
                'kode_pos' => '35384',
                'jabatan' => 'Guru Olahraga',
                'status' => 'Aktif',
                'tanggal_masuk' => '2012-09-15',
            ],

            // Guru Olahraga Kelas 5
            [
                'user_id' => null,
                'nip' => '199304252022032203',
                'nama_lengkap' => 'Rendi Saputra, S.Pd.',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Pringsewu',
                'tanggal_lahir' => '1993-04-25',
                'agama' => 'Islam',
                'nik' => '1878042504930003',
                'nomor_telepon' => '082345678901',
                'email' => 'rendi.saputra@sekolah.sch.id',
                'alamat' => 'Jl. Raya Pringsewu No. 22',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Pringsewu',
                'kecamatan' => 'Pringsewu Utara',
                'kelurahan' => 'Pringsewu',
                'dusun' => 'Pringsewu Timur',
                'kode_pos' => '35373',
                'jabatan' => 'Guru Olahraga',
                'status' => 'Aktif',
                'tanggal_masuk' => '2023-02-15',
            ],

            // Guru Olahraga Kelas 6
            [
                'user_id' => null,
                'nip' => '198712052015032204',
                'nama_lengkap' => 'Mega Wati, S.Pd.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Lampung Barat',
                'tanggal_lahir' => '1987-12-05',
                'agama' => 'Islam',
                'nik' => '1876120512870004',
                'nomor_telepon' => '081456789012',
                'email' => 'mega.wati@sekolah.sch.id',
                'alamat' => 'Jl. Lintas Liwa No. 15',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Lampung Barat',
                'kecamatan' => 'Balik Bukit',
                'kelurahan' => 'Pasar Liwa',
                'dusun' => 'Liwa Selatan',
                'kode_pos' => '34815',
                'jabatan' => 'Guru Olahraga',
                'status' => 'Aktif',
                'tanggal_masuk' => '2017-08-20',
            ],

            // ==================== GURU MENGAJI (3 guru) ====================
            // Guru Mengaji Kelas 1
            [
                'user_id' => null,
                'nip' => '197512102005011007',
                'nama_lengkap' => 'KH. Abdullah Syafei',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Lampung Barat',
                'tanggal_lahir' => '1975-12-10',
                'agama' => 'Islam',
                'nik' => '1876121012750007',
                'nomor_telepon' => '081678901234',
                'email' => 'abdullah.syafei@sekolah.sch.id',
                'alamat' => 'Jl. Lintas Liwa No. 1',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Lampung Barat',
                'kecamatan' => 'Balik Bukit',
                'kelurahan' => 'Pasar Liwa',
                'dusun' => 'Liwa Raya',
                'kode_pos' => '34815',
                'jabatan' => 'Guru Mengaji',
                'status' => 'Aktif',
                'tanggal_masuk' => '2008-01-05',
            ],

            // Guru Mengaji Kelas 2
            [
                'user_id' => null,
                'nip' => '198011252010042008',
                'nama_lengkap' => 'Ummi Kalsum, S.Ag.',
                'jenis_kelamin' => 'Perempuan',
                'tempat_lahir' => 'Tanggamus',
                'tanggal_lahir' => '1980-11-25',
                'agama' => 'Islam',
                'nik' => '1877112511800008',
                'nomor_telepon' => '081789012345',
                'email' => 'ummi.kalsum@sekolah.sch.id',
                'alamat' => 'Jl. Raya Kota Agung No. 5',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Tanggamus',
                'kecamatan' => 'Kota Agung',
                'kelurahan' => 'Kota Agung',
                'dusun' => 'Kota Agung Pusat',
                'kode_pos' => '35384',
                'jabatan' => 'Guru Mengaji',
                'status' => 'Aktif',
                'tanggal_masuk' => '2013-08-15',
            ],

            // Guru Mengaji Kelas 3
            [
                'user_id' => null,
                'nip' => '199305152020032009',
                'nama_lengkap' => 'Muhammad Fauzan, S.Pd.I.',
                'jenis_kelamin' => 'Laki-laki',
                'tempat_lahir' => 'Pringsewu',
                'tanggal_lahir' => '1993-05-15',
                'agama' => 'Islam',
                'nik' => '1878051505930009',
                'nomor_telepon' => '082456789012',
                'email' => 'muhammad.fauzan@sekolah.sch.id',
                'alamat' => 'Jl. Raya Pringsewu No. 9',
                'provinsi' => 'Lampung',
                'kabupaten' => 'Pringsewu',
                'kecamatan' => 'Pringsewu',
                'kelurahan' => 'Fajar Agung',
                'dusun' => 'Fajar Agung Barat',
                'kode_pos' => '35373',
                'jabatan' => 'Guru Mengaji',
                'status' => 'Aktif',
                'tanggal_masuk' => '2021-03-01',
            ],
        ];

        // Insert data ke tabel teachers
        foreach ($teachers as $teacher) {
            DB::table('teachers')->insert([
                ...$teacher,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]);
        }

        $this->command->info('Seeder teachers berhasil ditambahkan!');
        $this->command->info('Total: ' . count($teachers) . ' guru');
        $this->command->info('================== DISTRIBUSI DAERAH LAMPUNG ==================');
        $this->command->info('Kota Bandar Lampung: 4 guru');
        $this->command->info('Kota Metro: 3 guru');
        $this->command->info('Lampung Selatan: 3 guru');
        $this->command->info('Lampung Tengah: 3 guru');
        $this->command->info('Lampung Timur: 3 guru');
        $this->command->info('Lampung Barat: 3 guru');
        $this->command->info('Tanggamus: 3 guru');
        $this->command->info('Pringsewu: 3 guru');
        $this->command->info('Way Kanan: 3 guru');
        $this->command->info('Lampung Utara: 1 guru');
        $this->command->info('Pesisir Barat: 1 guru');
        $this->command->info('================== DISTRIBUSI JABATAN ==================');
        $this->command->info('Wali Kelas: 18 guru (untuk kelas 1A-6C)');
        $this->command->info('Guru Olahraga: 6 guru (1 guru per tingkat 1-6)');
        $this->command->info('Guru Mengaji: 3 guru (1 guru untuk tingkat 1, 2, dan 3)');
        $this->command->info('Total Guru: 27 guru (semua status Aktif)');
    }
}
